// Code generated by goctl. DO NOT EDIT.
package types

type CreateOrderRequest struct {
	Token string `header:"token"`
}

type CreateOrderResponse struct {
	Price      float32 `json:"price"`
	UserId     int32   `json:"user_id"`
	OrderId    int32   `json:"order_id"`
	CreateTime int64   `json:"create_time"`
}

type CreateSeckillOrderResponse struct {
	Price  float32 `json:"price"`
	UserId int32   `json:"user_id"`
}

type CreateSeckillRequest struct {
	Token  string `header:"token"`
	ItemId int32  `json:"item_id"`
}
