// Code generated by goctl. DO NOT EDIT.
// Source: payment_rpc.proto

package payment

import (
	"context"

	"Final_Assessment/lhy_payment/payment_rpc/types/payment_rpc"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	DeductAccountRequest  = payment_rpc.DeductAccountRequest
	DeductAccountResponse = payment_rpc.DeductAccountResponse

	Payment interface {
		DeductAccount(ctx context.Context, in *DeductAccountRequest, opts ...grpc.CallOption) (*DeductAccountResponse, error)
	}

	defaultPayment struct {
		cli zrpc.Client
	}
)

func NewPayment(cli zrpc.Client) Payment {
	return &defaultPayment{
		cli: cli,
	}
}

func (m *defaultPayment) DeductAccount(ctx context.Context, in *DeductAccountRequest, opts ...grpc.CallOption) (*DeductAccountResponse, error) {
	client := payment_rpc.NewPaymentClient(m.cli.Conn())
	return client.DeductAccount(ctx, in, opts...)
}
