// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"Final_Assessment/lhy_cart/cart_api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/api/item",
				Handler: itemHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/item",
				Handler: getItemsHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/api/item",
				Handler: deleteItemHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/item/cart",
				Handler: cartHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/item/cart",
				Handler: getCartHandler(serverCtx),
			},
		},
	)
}
