// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v3.19.4
// source: stock_rpc.proto

package stock_rpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ReduceInventoryRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ItemId int32 `protobuf:"varint,1,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
}

func (x *ReduceInventoryRequest) Reset() {
	*x = ReduceInventoryRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_stock_rpc_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReduceInventoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReduceInventoryRequest) ProtoMessage() {}

func (x *ReduceInventoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stock_rpc_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReduceInventoryRequest.ProtoReflect.Descriptor instead.
func (*ReduceInventoryRequest) Descriptor() ([]byte, []int) {
	return file_stock_rpc_proto_rawDescGZIP(), []int{0}
}

func (x *ReduceInventoryRequest) GetItemId() int32 {
	if x != nil {
		return x.ItemId
	}
	return 0
}

type ReduceInventoryResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Msg string `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *ReduceInventoryResponse) Reset() {
	*x = ReduceInventoryResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_stock_rpc_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReduceInventoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReduceInventoryResponse) ProtoMessage() {}

func (x *ReduceInventoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stock_rpc_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReduceInventoryResponse.ProtoReflect.Descriptor instead.
func (*ReduceInventoryResponse) Descriptor() ([]byte, []int) {
	return file_stock_rpc_proto_rawDescGZIP(), []int{1}
}

func (x *ReduceInventoryResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

var File_stock_rpc_proto protoreflect.FileDescriptor

var file_stock_rpc_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x73, 0x74, 0x6f, 0x63, 0x6b, 0x5f, 0x72, 0x70, 0x63, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x09, 0x73, 0x74, 0x6f, 0x63, 0x6b, 0x5f, 0x72, 0x70, 0x63, 0x22, 0x31, 0x0a, 0x16,
	0x52, 0x65, 0x64, 0x75, 0x63, 0x65, 0x49, 0x6e, 0x76, 0x65, 0x6e, 0x74, 0x6f, 0x72, 0x79, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x69, 0x74, 0x65, 0x6d, 0x5f, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x69, 0x74, 0x65, 0x6d, 0x49, 0x64, 0x22,
	0x2b, 0x0a, 0x17, 0x52, 0x65, 0x64, 0x75, 0x63, 0x65, 0x49, 0x6e, 0x76, 0x65, 0x6e, 0x74, 0x6f,
	0x72, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73,
	0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x32, 0xc3, 0x01, 0x0a,
	0x05, 0x73, 0x74, 0x6f, 0x63, 0x6b, 0x12, 0x58, 0x0a, 0x0f, 0x52, 0x65, 0x64, 0x75, 0x63, 0x65,
	0x49, 0x6e, 0x76, 0x65, 0x6e, 0x74, 0x6f, 0x72, 0x79, 0x12, 0x21, 0x2e, 0x73, 0x74, 0x6f, 0x63,
	0x6b, 0x5f, 0x72, 0x70, 0x63, 0x2e, 0x52, 0x65, 0x64, 0x75, 0x63, 0x65, 0x49, 0x6e, 0x76, 0x65,
	0x6e, 0x74, 0x6f, 0x72, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x22, 0x2e, 0x73,
	0x74, 0x6f, 0x63, 0x6b, 0x5f, 0x72, 0x70, 0x63, 0x2e, 0x52, 0x65, 0x64, 0x75, 0x63, 0x65, 0x49,
	0x6e, 0x76, 0x65, 0x6e, 0x74, 0x6f, 0x72, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x60, 0x0a, 0x17, 0x52, 0x65, 0x64, 0x75, 0x63, 0x65, 0x49, 0x6e, 0x76, 0x65, 0x6e, 0x74,
	0x6f, 0x72, 0x79, 0x52, 0x6f, 0x6c, 0x6c, 0x42, 0x61, 0x63, 0x6b, 0x12, 0x21, 0x2e, 0x73, 0x74,
	0x6f, 0x63, 0x6b, 0x5f, 0x72, 0x70, 0x63, 0x2e, 0x52, 0x65, 0x64, 0x75, 0x63, 0x65, 0x49, 0x6e,
	0x76, 0x65, 0x6e, 0x74, 0x6f, 0x72, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x22,
	0x2e, 0x73, 0x74, 0x6f, 0x63, 0x6b, 0x5f, 0x72, 0x70, 0x63, 0x2e, 0x52, 0x65, 0x64, 0x75, 0x63,
	0x65, 0x49, 0x6e, 0x76, 0x65, 0x6e, 0x74, 0x6f, 0x72, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x42, 0x0d, 0x5a, 0x0b, 0x2e, 0x2f, 0x73, 0x74, 0x6f, 0x63, 0x6b, 0x5f, 0x72, 0x70,
	0x63, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_stock_rpc_proto_rawDescOnce sync.Once
	file_stock_rpc_proto_rawDescData = file_stock_rpc_proto_rawDesc
)

func file_stock_rpc_proto_rawDescGZIP() []byte {
	file_stock_rpc_proto_rawDescOnce.Do(func() {
		file_stock_rpc_proto_rawDescData = protoimpl.X.CompressGZIP(file_stock_rpc_proto_rawDescData)
	})
	return file_stock_rpc_proto_rawDescData
}

var file_stock_rpc_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_stock_rpc_proto_goTypes = []interface{}{
	(*ReduceInventoryRequest)(nil),  // 0: stock_rpc.ReduceInventoryRequest
	(*ReduceInventoryResponse)(nil), // 1: stock_rpc.ReduceInventoryResponse
}
var file_stock_rpc_proto_depIdxs = []int32{
	0, // 0: stock_rpc.stock.ReduceInventory:input_type -> stock_rpc.ReduceInventoryRequest
	0, // 1: stock_rpc.stock.ReduceInventoryRollBack:input_type -> stock_rpc.ReduceInventoryRequest
	1, // 2: stock_rpc.stock.ReduceInventory:output_type -> stock_rpc.ReduceInventoryResponse
	1, // 3: stock_rpc.stock.ReduceInventoryRollBack:output_type -> stock_rpc.ReduceInventoryResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_stock_rpc_proto_init() }
func file_stock_rpc_proto_init() {
	if File_stock_rpc_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_stock_rpc_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReduceInventoryRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_stock_rpc_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReduceInventoryResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_stock_rpc_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_stock_rpc_proto_goTypes,
		DependencyIndexes: file_stock_rpc_proto_depIdxs,
		MessageInfos:      file_stock_rpc_proto_msgTypes,
	}.Build()
	File_stock_rpc_proto = out.File
	file_stock_rpc_proto_rawDesc = nil
	file_stock_rpc_proto_goTypes = nil
	file_stock_rpc_proto_depIdxs = nil
}
