// Code generated by goctl. DO NOT EDIT.
// Source: payment_rpc.proto

package server

import (
	"context"

	"Final_Assessment/lhy_payment/payment_rpc/internal/logic"
	"Final_Assessment/lhy_payment/payment_rpc/internal/svc"
	"Final_Assessment/lhy_payment/payment_rpc/types/payment_rpc"
)

type PaymentServer struct {
	svcCtx *svc.ServiceContext
	payment_rpc.UnimplementedPaymentServer
}

func NewPaymentServer(svcCtx *svc.ServiceContext) *PaymentServer {
	return &PaymentServer{
		svcCtx: svcCtx,
	}
}

func (s *PaymentServer) DeductAccount(ctx context.Context, in *payment_rpc.DeductAccountRequest) (*payment_rpc.DeductAccountResponse, error) {
	l := logic.NewDeductAccountLogic(ctx, s.svcCtx)
	return l.DeductAccount(in)
}
