// Code generated by goctl. DO NOT EDIT.
// Source: stock_rpc.proto

package server

import (
	"context"

	"Final_Assessment/lhy_stock/stock_rpc/internal/logic"
	"Final_Assessment/lhy_stock/stock_rpc/internal/svc"
	"Final_Assessment/lhy_stock/stock_rpc/types/stock_rpc"
)

type StockServer struct {
	svcCtx *svc.ServiceContext
	stock_rpc.UnimplementedStockServer
}

func NewStockServer(svcCtx *svc.ServiceContext) *StockServer {
	return &StockServer{
		svcCtx: svcCtx,
	}
}

func (s *StockServer) ReduceInventory(ctx context.Context, in *stock_rpc.ReduceInventoryRequest) (*stock_rpc.ReduceInventoryResponse, error) {
	l := logic.NewReduceInventoryLogic(ctx, s.svcCtx)
	return l.ReduceInventory(in)
}

func (s *StockServer) ReduceInventoryRollBack(ctx context.Context, in *stock_rpc.ReduceInventoryRequest) (*stock_rpc.ReduceInventoryResponse, error) {
	l := logic.NewReduceInventoryRollBackLogic(ctx, s.svcCtx)
	return l.ReduceInventoryRollBack(in)
}
