// Code generated by goctl. DO NOT EDIT.
// Source: stock_rpc.proto

package stock

import (
	"context"

	"Final_Assessment/lhy_stock/stock_rpc/types/stock_rpc"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	ReduceInventoryRequest  = stock_rpc.ReduceInventoryRequest
	ReduceInventoryResponse = stock_rpc.ReduceInventoryResponse

	Stock interface {
		ReduceInventory(ctx context.Context, in *ReduceInventoryRequest, opts ...grpc.CallOption) (*ReduceInventoryResponse, error)
		ReduceInventoryRollBack(ctx context.Context, in *ReduceInventoryRequest, opts ...grpc.CallOption) (*ReduceInventoryResponse, error)
	}

	defaultStock struct {
		cli zrpc.Client
	}
)

func NewStock(cli zrpc.Client) Stock {
	return &defaultStock{
		cli: cli,
	}
}

func (m *defaultStock) ReduceInventory(ctx context.Context, in *ReduceInventoryRequest, opts ...grpc.CallOption) (*ReduceInventoryResponse, error) {
	client := stock_rpc.NewStockClient(m.cli.Conn())
	return client.ReduceInventory(ctx, in, opts...)
}

func (m *defaultStock) ReduceInventoryRollBack(ctx context.Context, in *ReduceInventoryRequest, opts ...grpc.CallOption) (*ReduceInventoryResponse, error) {
	client := stock_rpc.NewStockClient(m.cli.Conn())
	return client.ReduceInventoryRollBack(ctx, in, opts...)
}
